CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;

CREATE TABLE Customer(
cID INT PRIMARY KEY AUTO_INCREMENT,
cName VARCHAR(45),
cAge INT
);

CREATE TABLE Orders(
oID INT PRIMARY KEY AUTO_INCREMENT,
cID INT,
FOREIGN KEY (cID) REFERENCES Customer(cID),
oDate DATE,
oTotalPrice VARCHAR(45)
);

CREATE TABLE Product(
pID INT PRIMARY KEY AUTO_INCREMENT,
pName VARCHAR(45),
pPrice VARCHAR(45)
);

CREATE TABLE OrderDetail(
oID INT,
pID INT,
PRIMARY KEY (oID,pID),
FOREIGN KEY (oID) REFERENCES Orders(oID),
FOREIGN KEY (pID) REFERENCES Product(pID)
);