CREATE DATABASE enterprise;
USE enterprise;
CREATE TABLE phieuXuat(
soPX INT PRIMARY KEY AUTO_INCREMENT,
ngayXuat DATE
);

CREATE TABLE vatTU(
maVTU INT PRIMARY KEY AUTO_INCREMENT,
tenVTU VARCHAR(45)
);

CREATE TABLE CT_phieuXuat(
soPX INT,
maVTU INT,
PRIMARY KEY(soPX,maVTU),
FOREIGN KEY(soPX) REFERENCES phieuXuat(soPX),
FOREIGN KEY(maVTU) REFERENCES vatTU(maVTU),
DGXuat VARCHAR(45),
SLXuat INT
);

CREATE TABLE phieuNhap(
soPN INT PRIMARY KEY AUTO_INCREMENT,
ngayNhap DATE
);

CREATE TABLE CT_phieuNhap(
maVTU INT,
soPN INT,
PRIMARY KEY(maVTU,soPN),
FOREIGN KEY(maVTU) REFERENCES vatTU(maVTU),
FOREIGN KEY(soPN) REFERENCES PHIEUNHAP(soPN),
DGNhap VARCHAR(45),
SLNhap INT
);

CREATE TABLE nhaCC(
maNCC INT PRIMARY KEY AUTO_INCREMENT,
tenNCC VARCHAR(45),
diaChi VARCHAR(45)
);

CREATE TABLE phone(
maNCC INT ,
numberPhone VARCHAR(45),
PRIMARY KEY(maNCC,numberPhone),
FOREIGN KEY(maNCC) REFERENCES nhaCC(maNCC)
);

CREATE TABLE donDH(
soDH INT PRIMARY KEY AUTO_INCREMENT,
ngayDH DATE,
maNCC INT,
FOREIGN KEY(maNCC) REFERENCES nhaCC(maNCC)
);

CREATE TABLE CT_donDH(
maVTU INT,
soDH INT,
PRIMARY KEY(maVTU,soDH),
FOREIGN KEY(maVTU) REFERENCES vatTU(maVTU),
FOREIGN KEY(soDH) REFERENCES donDH(soDH)
);
